//to generate coverage report call "debugCoverage" and "jacocoTestReport" tasks
project.plugins.apply('jacoco')

project.jacoco {
    toolVersion '0.8.10'
}

project.tasks.withType(Test).configureEach {
    it.jacoco.includeNoLocationClasses = true
    it.jacoco.excludes = ['jdk.internal.*']
}

if (!project.plugins.hasPlugin('com.android.library')) {
    project.tasks.named('jacocoTestReport', JacocoReport) {
        group = "Reporting"
        description = "Generates Jacoco coverage reports."
        dependsOn(project.tasks.named('test'))
        reports {
            xml.required = true
            html.required = true
        }
        executionData.from = fileTree(dir: project.projectDir, includes: ["**/*.exec", "**/*.ec"])
    }
    project.tasks.register('debugCoverage') {
        group = 'Verification'
        description = 'Runs Jacoco coverage reports for the debug build.'
        dependsOn(project.tasks.named('jacocoTestReport'))
    }
    return
}

createCoverageTask('debug', 'connectedDebugAndroidTest', 'testDebugUnitTest', project)

private def createCoverageTask(variantName, uiTestTaskName, unitTestTaskName, final Project project) {
    return project.tasks.register("${variantName}Coverage", JacocoReport) {
        group = "Reporting"
        description = "Generate Jacoco coverage reports for the ${variantName} build."
        dependsOn(uiTestTaskName, unitTestTaskName)
        reports {
            xml.required = true
            html.required = true
        }
        def excludes = [
                '**/R.class',
                '**/R$*.class',
                '**/BuildConfig.*',
                '**/Manifest*.*',
                '**/*Test*.*',
                'android/**/*.*',
                'androidx/**/*.*',
                '**/*$ViewInjector*.*',
                '**/*Dagger*.*',
                '**/*MembersInjector*.*',
                '**/*_Factory.*',
                '**/*_Provide*Factory*.*',
                '**/*_ViewBinding*.*',
                '**/AutoValue_*.*',
                '**/R2.class',
                '**/R2$*.class',
                '**/*Directions$*',
                '**/*Directions.*',
                '**/*Binding.*'
        ]
        def jClassDir = project.layout.buildDirectory.dir("intermediates/javac/${variantName}").get().asFile
        def kClassDir = project.layout.buildDirectory.dir("tmp/kotlin-classes/${variantName}").get().asFile
        def javaClasses = fileTree(dir: jClassDir, includes: ['**/classes/**'], excludes: excludes)
        def kotlinClasses = fileTree(dir: kClassDir, excludes: excludes)
        classDirectories.from = files([javaClasses, kotlinClasses])
        def sourceDirs = [
                "${project.projectDir}/src/main/java",
                "${project.projectDir}/src/main/kotlin",
                "${project.projectDir}/src/${variantName}/java",
                "${project.projectDir}/src/${variantName}/kotlin"
        ]
        sourceDirectories.from = files(sourceDirs)
        executionData.from = fileTree(dir: project.projectDir, includes: ["**/*.exec", "**/*.ec"])
    }
}
